name: Build & Push Docker image to GHCR

on:
  push:
    branches: [ main ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: demo-crm

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
   
    - name: Generate image tag
      id: generate-tag
      run: |
        TAG="build-$(date +%Y%m%d)-${GITHUB_SHA:0:7}"
        echo "tag=${TAG}" >> $GITHUB_OUTPUT
        echo "Generated tag: ${TAG}"

    - name: Log in to GHCR
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GHCR_TOKEN }}

    - name: Pull, retag and push Demo CRM image
      run: |
        TAG="${{ steps.generate-tag.outputs.tag }}"
        IMAGE_NAME="${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}"
        
        echo "Pulling original image..."
        docker pull pwstaging/demo-crm:latest
        
        echo "Retagging image..."
        docker tag pwstaging/demo-crm:latest ${IMAGE_NAME}:${TAG}
        docker tag pwstaging/demo-crm:latest ${IMAGE_NAME}:latest
        
        echo "Pushing images..."
        docker push ${IMAGE_NAME}:${TAG}
        docker push ${IMAGE_NAME}:latest
        
        echo "Images pushed successfully"

    # - name: Build and push Docker image
    #   run: |
    #     IMAGE=${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}
    #     TAG=latest

    #     docker build -t $IMAGE:$TAG .
    #     docker push $IMAGE:$TAG

    #     echo "Image pushed: $IMAGE:$TAG"
